spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/homepage_db?serverTimezone=Asia/Seoul
    username: root
    password: 9610

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration